<?php

namespace AppBundle\Repository\Gestor\Acesso;

use Doctrine\ORM\EntityRepository;

/**
 * GestorUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestorUserRepository extends EntityRepository
{
    public function checkUniqueEmail($emailCononical)
    {
        return $this->createQueryBuilder('g')
            ->select('g.id')
            ->innerJoin('g.user','u')
            ->andWhere('u.emailCanonical = :emailCanonical')->setParameter('emailCanonical', $emailCononical)
            ->andWhere('u.roles like :role')->setParameter(':role', '%ROLE_GESTOR_USER%')
            ->getQuery()
            ->getOneOrNullResult();
    }
}
