# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_GESTOR_CONTENT: [ROLE_GESTOR_USER, ROLE_GESTOR_SUPER_ADMIN]
        ROLE_ADMIN_CONTENT: [ROLE_ADMIN_USER, ROLE_ADMIN_SUPER_ADMIN]
        ROLE_PORTAL_CONTENT: [ROLE_PORTAL_USER, ROLE_PORTAL_SUPER_ADMIN]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [in_memory, database_users]
        in_memory:
            memory:
                users:
                    admin: { password:  $2y$13$xbu9fVXYDD36mx42YT6k2ujz79DcJ7g6cOBeiBkkoB0ViIbd46Qqe, roles: [ROLE_GESTOR_USER,ROLE_GESTOR_SUPER_ADMIN] }
        database_users:
            entity: { class: AppBundle:User, property: email }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        gestor:
            anonymous: ~
            pattern: ^/gestor
            knpu_guard:
                authenticators:
                    - app.gestor_form_login_authenticator
            logout:
                path: gestor_security_logout
                target: gestor_security_login

        admin:
            anonymous: ~
            pattern: ^/admin
            knpu_guard:
                authenticators:
                    - app.admin_form_login_authenticator
            logout:
                path: admin_security_logout
                target: admin_security_login

    access_control:

        - { path: ^/gestor/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/gestor/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/gestor/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/gestor/, role: ROLE_GESTOR_USER }

        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN_USER }





            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
