<?php

namespace AppBundle\Repository\Admin\Acesso;

use Doctrine\ORM\EntityRepository;

/**
 * AdminUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminUserRepository extends EntityRepository
{
    public function checkUniqueEmail($emailCononical)
    {
        return $this->createQueryBuilder('a')
            ->select('a.id')
            ->innerJoin('a.user','u')
            ->andWhere('u.emailCanonical = :emailCanonical')->setParameter('emailCanonical', $emailCononical)
            ->andWhere('u.roles like :role')->setParameter(':role', '%ROLE_ADMIN_USER%')
            ->getQuery()
            ->getOneOrNullResult();
    }
}
